# 文件签名数据库

FILE_SIGNATURES = {
    # 图像文件
    'JPEG': {'signature': b'\xff\xd8\xff', 'description': 'JPEG图像文件', 'extension': '.jpg,.jpeg'}, 
    'PNG': {'signature': b'\x89\x50\x4e\x47\x0d\x0a\x1a\x0a', 'description': 'PNG图像文件', 'extension': '.png'}, 
    'GIF': {'signature': b'\x47\x49\x46\x38', 'description': 'GIF图像文件', 'extension': '.gif'}, 
    'BMP': {'signature': b'\x42\x4d', 'description': 'BMP图像文件', 'extension': '.bmp'}, 
    'TIFF': {'signature': b'\x49\x49\x2a\x00', 'description': 'TIFF图像文件', 'extension': '.tiff,.tif'}, 
    
    # 文档文件
    'PDF': {'signature': b'\x25\x50\x44\x46', 'description': 'PDF文档', 'extension': '.pdf'}, 
    'DOCX': {'signature': b'\x50\x4b\x03\x04\x14\x00\x06\x00', 'description': 'Microsoft Word文档', 'extension': '.docx'}, 
    'XLSX': {'signature': b'\x50\x4b\x03\x04\x14\x00\x06\x00', 'description': 'Microsoft Excel表格', 'extension': '.xlsx'}, 
    'PPTX': {'signature': b'\x50\x4b\x03\x04\x14\x00\x06\x00', 'description': 'Microsoft PowerPoint演示文稿', 'extension': '.pptx'}, 
    'ZIP': {'signature': b'\x50\x4b\x03\x04', 'description': 'ZIP压缩文件', 'extension': '.zip'}, 
    'RAR': {'signature': b'\x52\x61\x72\x21\x1a\x07\x00', 'description': 'RAR压缩文件', 'extension': '.rar'}, 
    '3GP': {'signature': b'\x66\x74\x79\x70\x33\x67\x70', 'description': '3GPP多媒体文件', 'extension': '.3gg,.3gp,.3g2'}, 
    'BZIP2': {'signature': b'\x42\x5A\x68', 'description': 'BZIP2压缩文件', 'extension': '.bz,.bz2,.tar.bz2,.tbz2,.tb2'}, 
    'CAB': {'signature': b'\x4D\x53\x43\x46', 'description': 'Microsoft CAB压缩文件', 'extension': '.cab'}, 
    '7Z': {'signature': b'\x37\x7a\xbc\xaf\x27\x1c', 'description': '7-Zip压缩文件', 'extension': '.7z'}, 
    'AMR': {'signature': b'\x23\x21\x41\x4d\x52', 'description': 'Adaptive Multi-Rate音频文件', 'extension': '.amr'}, 
    'ASF': {'signature': b'\x30\x26\xb2\x75\x8e\x66\xcf\x11', 'description': '高级流格式文件', 'extension': '.asf,.wma,.wmv'}, 
    'CHM': {'signature': b'\x49\x54\x53\x46', 'description': '编译HTML帮助文件', 'extension': '.chm'}, 
    'AIFF': {'signature': b'\x46\x4F\x52\x4D\x00', 'description': 'Audio Interchange File', 'extension': '.aiff'}, 
    'AU': {'signature': b'\x2E\x73\x6E\x64', 'description': 'Sun Microsystems音频文件', 'extension': '.au'}, 
    'ARJ': {'signature': b'\x60\xEA', 'description': 'ARJ压缩文件', 'extension': '.arj'}, 
    'ASX': {'signature': b'<', 'description': '高级流重定向器文件', 'extension': '.asx'}, 
    'FLAC': {'signature': b'\x66\x4C\x61\x43', 'description': 'FLAC音频文件', 'extension': '.flac'}, 
    'MID': {'signature': b'\x4D\x54\x68\x64', 'description': 'MIDI音频文件', 'extension': '.mid,.midi'}, 
    'MOV': {'signature': b'\x6D\x6F\x6F\x76', 'description': 'QuickTime视频文件', 'extension': '.mov'}, 
    'MPG': {'signature': b'\x00\x00\x01\xBA', 'description': 'MPEG视频文件', 'extension': '.mpg,.mpeg'}, 
    'OGG': {'signature': b'\x4F\x67\x67\x53', 'description': 'OGG容器格式', 'extension': '.ogg'}, 
    'CRW': {'signature': b'\x49\x49\x1a\x00\x00\x00\x48\x45', 'description': 'Canon RAW图像文件', 'extension': '.crw'}, 
    'CUR': {'signature': b'\x00\x00\x02\x00\x01\x00\x20\x20', 'description': 'Windows光标文件', 'extension': '.cur'}, 
    'CPL': {'signature': b'\x4D\x5A', 'description': '控制面板应用程序', 'extension': '.cpl'}, 
    'CPT': {'signature': b'\x43\x50\x54\x37\x46\x49\x4C\x45', 'description': 'Corel Photopaint文件', 'extension': '.cpt'}, 
    'DBF': {'signature': b'\x03\x00', 'description': 'dBASE数据库文件', 'extension': '.dbf'}, 
    'DIB': {'signature': b'\x42\x4D', 'description': '设备无关位图', 'extension': '.dib'}, 
    'ADX': {'signature': b'\x03\x00\x00\x00\x41\x50\x50\x52', 'description': 'Lotus Approach ADX文件', 'extension': '.adx'}, 
    'AIN': {'signature': b'\x21\x12', 'description': 'AIN压缩档案文件', 'extension': '.ain'}, 
    'AMI': {'signature': b'\x5B\x76\x65\x72\x5D', 'description': 'Lotus Ami Pro文件', 'extension': '.ami'}, 
    'ART': {'signature': b'\x4A\x47\x03\x0E\x00\x00\x00', 'description': 'AOL ART文件', 'extension': '.art'}, 
    'CPE': {'signature': b'\x46\x41\x58\x43\x4F\x56\x45\x52\x2D\x56\x45\x52', 'description': 'Microsoft Fax封面文件', 'extension': '.cpe'}, 
    'ANI': {'signature': b'\x52\x49\x46\x46', 'description': 'Windows动画光标文件', 'extension': '.ani'}, 
    'ACCDB': {'signature': b'\x00\x01\x00\x00\x53\x74\x61\x6E\x64\x61\x72\x64\x20\x41\x43\x45\x20\x44\x42', 'description': 'Microsoft Access 2007数据库文件', 'extension': '.accdb'}, 
    'ACM': {'signature': b'\x4D\x5A', 'description': 'MS音频压缩管理器驱动', 'extension': '.acm'}, 
    'ADF': {'signature': b'\x44\x4F\x53', 'description': 'Amiga磁盘文件', 'extension': '.adf'}, 
    'API': {'signature': b'\x4D\x5A\x90\x00\x03\x00\x00\x00', 'description': 'Acrobat插件', 'extension': '.api'}, 
    'ARC': {'signature': b'\x41\x72\x43\x01', 'description': 'FreeArc压缩文件', 'extension': '.arc'}, 
    'CAB_INSTALLSHIELD': {'signature': b'\x49\x53\x63\x28', 'description': 'InstallShield压缩文件', 'extension': '.cab,.hdr'}, 
    'CAT': {'signature': b'\x30', 'description': 'Microsoft安全目录文件', 'extension': '.cat'}, 
    'CBD': {'signature': b'\x43\x42\x46\x49\x4C\x45', 'description': 'WordPerfect字典文件', 'extension': '.cbd'}, 
    'CCD': {'signature': b'\x5B\x43\x6C', 'description': 'CloneCD控制文件', 'extension': '.ccd'}, 
    'CDR_COREL': {'signature': b'\x45\x4C\x49\x54\x54\x20\x43\x6F\x6D\x6D\x61\x6E\x64\x65\x72\x20', 'description': 'Corel Draw文件', 'extension': '.cdr'}, 
    'CLB': {'signature': b'\x43\x4D\x5A\x31', 'description': 'Corel Binary元文件', 'extension': '.clb'}, 
    'CNT': {'signature': b'\x3A\x42\x61\x73\x65', 'description': 'COM+目录文件', 'extension': '.cnt'}, 
    'COM': {'signature': b'\x4D\x5A\xEE', 'description': 'DOS可执行文件', 'extension': '.com'}, 
    'CRU': {'signature': b'\x43\x52\x55\x53\x48', 'description': 'CRUSH压缩档案', 'extension': '.cru,.crush'}, 
    'CTF': {'signature': b'\x43\x61\x74\x61\x6C\x6F\x67\x20\x33\x2E\x30\x30\x00', 'description': 'WhereIsIt目录文件', 'extension': '.ctf'}, 
    'ABA': {'signature': b'\x00\x01\x42\x41', 'description': 'Palm Address Book Archive', 'extension': '.aba'}, 
    'ABI': {'signature': b'\x41\x4F\x4C\x49\x4E\x44\x45\x58', 'description': 'AOL地址簿索引文件', 'extension': '.abi'}, 
    'ABY': {'signature': b'\x41\x4F\x4C\x44\x42', 'description': 'AOL数据库文件', 'extension': '.aby,.idx'}, 
    'AX': {'signature': b'\x4D\x5A', 'description': '库缓存文件', 'extension': '.ax'}, 
    'BAG': {'signature': b'\x41\x4F\x4C\x20\x46\x65\x65\x64\x62\x61\x67', 'description': 'AOL好友列表文件', 'extension': '.bag'}, 
    'BAS': {'signature': b'\x20\x20\x20', 'description': 'BASIC源代码文件', 'extension': '.bas'}, 
    'BIN_SPEEDTOUCH': {'signature': b'\x42\x4C\x49\x32\x32\x33\x51', 'description': 'Thomson Speedtouch固件', 'extension': '.bin'}, 
    'AAC': {'signature': b'\x00\x00\x00\x00\x66\x74\x79\x70\x6D\x70\x34\x32', 'description': 'AAC音频文件', 'extension': '.aac'}, 
    'AI': {'signature': b'\x25\x50\x44\x46\x2D\x31\x2E\x35', 'description': 'Adobe Illustrator文件', 'extension': '.ai'}, 
    'APK': {'signature': b'\x50\x4B\x03\x04', 'description': 'Android应用包', 'extension': '.apk'}, 
    'ARW': {'signature': b'\x49\x49\x1a\x00\x00\x00\x48\x45', 'description': 'Sony RAW图像文件', 'extension': '.arw'}, 
    'BAT': {'signature': b'', 'description': '批处理文件', 'extension': '.bat'}, 
    'CBR': {'signature': b'\x52\x61\x72\x21\x1a\x07\x00', 'description': '漫画书RAR归档', 'extension': '.cbr'}, 
    'CGM': {'signature': b'\x47\x43\x4D', 'description': '计算机图形元文件', 'extension': '.cgm'}, 
    'CLASS': {'signature': b'\xCA\xFE\xBA\xBE', 'description': 'Java类文件', 'extension': '.class'}, 
    'CSS': {'signature': b'/*', 'description': '层叠样式表', 'extension': '.css'}, 
    'DCM': {'signature': b'\x44\x49\x43\x4D', 'description': 'DICOM医学图像', 'extension': '.dcm'}, 
    'DMG': {'signature': b'\x78\x01\x73\x0D\x62\x62\x60', 'description': 'Apple磁盘镜像', 'extension': '.dmg'}, 
    'DNG': {'signature': b'\x49\x49\x2A\x00\x08\x00\x00\x00', 'description': 'Adobe数字负片', 'extension': '.dng'}, 
    'ICO': {'signature': b'\x00\x00\x01\x00', 'description': 'Windows图标文件', 'extension': '.ico'}, 
    'ISO': {'signature': b'\x43\x44\x30\x30\x31', 'description': 'ISO光盘镜像文件', 'extension': '.iso'}, 
    'MDB': {'signature': b'\x00\x01\x00\x00\x53\x74\x61\x6E\x64\x61\x72\x64\x20\x4A\x65\x74\x20\x44\x42', 'description': 'Microsoft Access数据库文件', 'extension': '.mdb'}, 
    'PSD': {'signature': b'\x38\x42\x50\x53', 'description': 'Adobe Photoshop文件', 'extension': '.psd'}, 
    
    # 可执行文件
    'EXE': {'signature': b'\x4d\x5a', 'description': 'Windows可执行文件', 'extension': '.exe'}, 
    'DLL': {'signature': b'\x4d\x5a', 'description': '动态链接库', 'extension': '.dll'}, 
    
    # 音频视频
    'MP4': {'signature': b'\x00\x00\x00\x18\x66\x74\x79\x70\x6d\x70\x34\x32', 'description': 'MP4视频文件', 'extension': '.mp4'}, 
    'AVI': {'signature': b'\x52\x49\x46\x46', 'description': 'AVI视频文件', 'extension': '.avi'}, 
    'MP3': {'signature': b'\xff\xfb', 'description': 'MP3音频文件', 'extension': '.mp3'}, 
    'WAV': {'signature': b'\x52\x49\x46\x46', 'description': 'WAV音频文件', 'extension': '.wav'}, 
    'EPUB': {'signature': b'\x50\x4B\x03\x04\x14\x00\x06\x00', 'description': '电子出版物文件', 'extension': '.epub'}, 
    'SQLITE': {'signature': b'\x53\x51\x4C\x69\x74\x65\x20\x66\x6F\x72\x6D\x61\x74\x20\x33\x00', 'description': 'SQLite数据库文件', 'extension': '.sqlite,.db'}, 
    'RAR5': {'signature': b'\x52\x61\x72\x21\x1A\x07\x01\x00', 'description': 'RAR5压缩文件', 'extension': '.rar'}, 
    'FLV': {'signature': b'\x46\x4C\x56\x01', 'description': 'Flash视频文件', 'extension': '.flv'}, 
    'SWF': {'signature': b'\x46\x57\x53', 'description': 'Shockwave Flash文件', 'extension': '.swf'}, 
    'WMV': {'signature': b'\x30\x26\xB2\x75\x8E\x66\xCF\x11\xA6\xD9\x00\xAA\x00\x62\xCE\x6C', 'description': 'Windows媒体视频', 'extension': '.wmv'}, 
    'MOBI': {'signature': b'\x4D\x4F\x42\x49', 'description': 'Mobipocket电子书', 'extension': '.mobi'}, 
    'GZIP': {'signature': b'\x1F\x8B', 'description': 'GNU压缩文件', 'extension': '.gz,.tar.gz,.tgz'}, 
    'WEBP': {'signature': b'\x52\x49\x46\x46\x00\x00\x00\x00\x57\x45\x42\x50', 'description': 'WebP图像文件', 'extension': '.webp'}, 
    'RTF': {'signature': b'{\\rtf', 'description': '富文本格式文件', 'extension': '.rtf'}, 
    'EPS': {'signature': b'%!PS-Adobe', 'description': 'Encapsulated PostScript文件', 'extension': '.eps'}, 
    'TORRENT': {'signature': b'd8:announce', 'description': 'BitTorrent元信息文件', 'extension': '.torrent'}, 
    'VSDX': {'signature': b'\x50\x4B\x03\x04\x14\x00\x06\x00', 'description': 'Microsoft Visio文件', 'extension': '.vsdx'}, 
    'XPS': {'signature': b'\x50\x4B\x03\x04', 'description': 'XML Paper Specification文件', 'extension': '.xps'}, 
    'TAR': {'signature': b'ustar\x00', 'description': 'TAR归档文件', 'extension': '.tar'}, 
    'VHD': {'signature': b'conectix', 'description': '虚拟硬盘文件', 'extension': '.vhd'}, 
    'VMDK': {'signature': b'\x4B\x44\x4D\x56', 'description': 'VMware虚拟磁盘', 'extension': '.vmdk'}, 
    'VOB': {'signature': b'\x00\x00\x01\xBA', 'description': 'DVD视频对象文件', 'extension': '.vob'}, 
    'MKV': {'signature': b'\x1A\x45\xDF\xA3', 'description': 'Matroska视频文件', 'extension': '.mkv'}, 
    'ODT': {'signature': b'\x50\x4B\x03\x04\x14\x00\x06\x00', 'description': 'OpenDocument文本文件', 'extension': '.odt'}, 
    'DOC': {'signature': b'\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1', 'description': 'Microsoft Word文档', 'extension': '.doc'}, 
    'PPT': {'signature': b'\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1', 'description': 'Microsoft PowerPoint演示文稿', 'extension': '.ppt'}, 
    'XLS': {'signature': b'\xD0\xCF\x11\xE0\xA1\xB1\x1A\xE1', 'description': 'Microsoft Excel表格', 'extension': '.xls'}, 
    'M4V': {'signature': b'\x00\x00\x00\x18\x66\x74\x79\x70\x6D\x70\x34\x32', 'description': 'M4V视频文件', 'extension': '.m4v'}, 
    'M4A': {'signature': b'\x00\x00\x00\x18\x66\x74\x79\x70\x6D\x70\x34\x32', 'description': 'M4A音频文件', 'extension': '.m4a'}, 
    'APNG': {'signature': b'\x89\x50\x4E\x47\x0D\x0A\x1A\x0A\x00\x00\x00\x0D\x49\x48\x44\x52', 'description': '动画PNG文件', 'extension': '.apng'}, 
    'AI': {'signature': b'\x25\x50\x44\x46\x2D\x31\x2E\x35', 'description': 'Adobe Illustrator文件', 'extension': '.ai'}, 
    'APK': {'signature': b'\x50\x4B\x03\x04', 'description': 'Android应用包', 'extension': '.apk'}, 
    'ARW': {'signature': b'\x49\x49\x1a\x00\x00\x00\x48\x45', 'description': 'Sony RAW图像文件', 'extension': '.arw'}, 
    'BAT': {'signature': b'', 'description': '批处理文件', 'extension': '.bat'}, 
    'CBR': {'signature': b'\x52\x61\x72\x21\x1a\x07\x00', 'description': '漫画书RAR归档', 'extension': '.cbr'}, 
    'CGM': {'signature': b'\x47\x43\x4D', 'description': '计算机图形元文件', 'extension': '.cgm'}, 
    'CLASS': {'signature': b'\xCA\xFE\xBA\xBE', 'description': 'Java类文件', 'extension': '.class'}, 
    'CSS': {'signature': b'/*', 'description': '层叠样式表', 'extension': '.css'}, 
    'DCM': {'signature': b'\x44\x49\x43\x4D', 'description': 'DICOM医学图像', 'extension': '.dcm'}, 
    'DMG': {'signature': b'\x78\x01\x73\x0D\x62\x62\x60', 'description': 'Apple磁盘镜像', 'extension': '.dmg'}, 
    'DNG': {'signature': b'\x49\x49\x2A\x00\x08\x00\x00\x00', 'description': 'Adobe数字负片', 'extension': '.dng'}, 
    'ICO': {'signature': b'\x00\x00\x01\x00', 'description': 'Windows图标文件', 'extension': '.ico'}, 
    'ISO': {'signature': b'\x43\x44\x30\x30\x31', 'description': 'ISO光盘镜像文件', 'extension': '.iso'}, 
    'MDB': {'signature': b'\x00\x01\x00\x00\x53\x74\x61\x6E\x64\x61\x72\x64\x20\x4A\x65\x74\x20\x44\x42', 'description': 'Microsoft Access数据库文件', 'extension': '.mdb'}, 
    'PSD': {'signature': b'\x38\x42\x50\x53', 'description': 'Adobe Photoshop文件', 'extension': '.psd'}, 
    
    # 可执行文件
    'EXE': {'signature': b'\x4d\x5a', 'description': 'Windows可执行文件', 'extension': '.exe'}, 
    'DLL': {'signature': b'\x4d\x5a', 'description': '动态链接库', 'extension': '.dll'}, 
    
    # 音频视频
    'MP4': {'signature': b'\x00\x00\x00\x18\x66\x74\x79\x70\x6d\x70\x34\x32', 'description': 'MP4视频文件', 'extension': '.mp4'}, 
    'AVI': {'signature': b'\x52\x49\x46\x46', 'description': 'AVI视频文件', 'extension': '.avi'}, 
    'MP3': {'signature': b'\xff\xfb', 'description': 'MP3音频文件', 'extension': '.mp3'}, 
    'WAV': {'signature': b'\x52\x49\x46\x46', 'description': 'WAV音频文件', 'extension': '.wav'}, 
    'EPUB': {'signature': b'\x50\x4B\x03\x04\x14\x00\x06\x00', 'description': '电子出版物文件', 'extension': '.epub'}, 
    'SQLITE': {'signature': b'\x53\x51\x4C\x69\x74\x65\x20\x66\x6F\x72\x6D\x61\x74\x20\x33\x00', 'description': 'SQLite数据库文件', 'extension': '.sqlite,.db'}, 
    'RAR5': {'signature': b'\x52\x61\x72\x21\x1A\x07\x01\x00', 'description': 'RAR5压缩文件', 'extension': '.rar'}, 
    'FLV': {'signature': b'\x46\x4C\x56\x01', 'description': 'Flash视频文件', 'extension': '.flv'}, 
    'SWF': {'signature': b'\x46\x57\x53', 'description': 'Shockwave Flash文件', 'extension': '.swf'}, 
    'WMV': {'signature': b'\x30\x26\xB2\x75\x8E\x66\xCF\x11\xA6\xD9\x00\xAA\x00\x62\xCE\x6C', 'description': 'Windows媒体视频', 'extension': '.wmv'}, 
    'MOBI': {'signature': b'\x4D\x4F\x42\x49', 'description': 'Mobipocket电子书', 'extension': '.mobi'}, 
    'GZIP': {'signature': b'\x1F\x8B', 'description': 'GNU压缩文件', 'extension': '.gz,.tar.gz,.tgz'}, 
    'WEBP': {'signature': b'\x52\x49\x46\x46\x00\x00\x00\x00\x57\x45\x42\x50', 'description': 'WebP图像文件', 'extension': '.webp'}, 
    'RTF': {'signature': b'{\\rtf', 'description': '富文本格式文件', 'extension': '.rtf'}, 
    'EPS': {'signature': b'%!PS-Adobe', 'description': 'Encapsulated PostScript文件', 'extension': '.eps'}, 
    'TORRENT': {'signature': b'd8:announce', 'description': 'BitTorrent元信息文件', 'extension': '.torrent'}, 
    'VSDX': {'signature': b'\x50\x4B\x03\x04\x14\x00\x06\x00', 'description': 'Microsoft Visio文件', 'extension': '.vsdx'}, 
    'XPS': {'signature': b'\x50\x4B\x03\x04', 'description': 'XML Paper Specification文件', 'extension': '.xps'}, 
    'TAR': {'signature': b'ustar\x00', 'description': 'TAR归档文件', 'extension': '.tar'}, 
    'VHD': {'signature': b'conectix', 'description': '虚拟硬盘文件', 'extension': '.vhd'}, 
    'VMDK': {'signature': b'KDMV', 'description': 'VMware虚拟磁盘', 'extension': '.vmdk'}, 
    'TXT': {'signature': b'', 'description': '文本文件', 'extension': '.txt'},  # 文本文件没有特定签名
    'CSV': {'signature': b'', 'description': '逗号分隔值文件', 'extension': '.csv'}, 
    'JSON': {'signature': b'{', 'description': 'JSON数据文件', 'extension': '.json'}, 
    'XML': {'signature': b'<?xml', 'description': 'XML标记语言文件', 'extension': '.xml'}, 
}

# 按签名长度排序，长签名优先匹配
SORTED_SIGNATURES = sorted(FILE_SIGNATURES.items(), key=lambda x: len(x[1]['signature']), reverse=True)